# Site settings
title: Cass Browne
email: cass.browne@googlemail.com
description: > # Cass Browne - Content Creator, Writer, Musician and Consultant
baseurl: "/cassbrowne"
url: "http://www.cassbrowne.com"

# Build settings
markdown: kramdown
